name: Operator checks

on:
  workflow_call:
    inputs:
      ie_type:
        description: 'Import Export type - project or dataset'
        type: string
        required: true
      image_path:
        description: 'Path for docker image'
        type: string
        required: true
      docker_image:
        description: 'Name of the docker image'
        type: string
        required: true

jobs:
  check1:
    name: Style Checks
    runs-on: ubuntu-latest
    outputs:
      components: "TEST"
    steps:
      - name: Run black
        run: echo ${{ inputs.ie_type }}
    

