name: One Big

on:
  workflow_call:
    inputs:
      check:
        required: true
        type: string
      mongo:
        required: false
        type: string

jobs:
  check1:
    if: inputs.check == 'check1'
    name: Style Checks
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: |
          echo "UNIT TEST - test"
  check2:
    if: inputs.check == 'check2'
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: |
          echo "UNIT TEST - test"
          echo ${{ inputs.mongo }}
