name: Operator checks

on:
  workflow_call:
    inputs:
      vcluster_name:
        description: 'Import Export type - project or dataset'
        type: string
        required: true

jobs:
  check1:
    name: Style Checks
    runs-on: ubuntu-latest
    outputs:
      components: "TEST"
    steps:
      - name: Run black
        run: |
          echo ${{ inputs.vcluster_name }}
    

