name: One Big

on:
  workflow_call:
    inputs:
      check:
        required: true
        type: string

jobs:
  check1:
    if: check == 'check1'
    name: Style Checks
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: |
          echo "UNIT TEST - test"
          exit 1
  check2:
    if: check == 'check2'
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: |
          echo "UNIT TEST - test"
