name: ${{operator_type}} operator checks

on:
  workflow_call:
    inputs:
      operator_type:
        required: true
        type: string

jobs:
  check1:
    name: Style Checks
    runs-on: ubuntu-latest
    container:
      image: ${{operator_type}}
    steps:
      - name: Upload coverage to artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-operator-${{operator_type}}
          path: |
            /root/coverage.xml
            /root/coverage_html
