name: Operator checks

on:
  workflow_call:
    inputs:
      operator_type:
        required: true
        type: string

jobs:
  check1:
    name: Style Checks
    runs-on: ubuntu-latest
    steps:
      - name: Run black
        working-directory: /usr/src/app/microservices/${{ inputs.ie_type }}_ie_microservice
        run: echo "TEST"
