# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  change-detection:
    name: Detect changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Store build params
        id: build_params
        run: |
          promoted_sha=$(git ls-remote https://github.com/intel-innersource/applications.ai.geti.application-stack release-1.13.0 | awk '{ print $1 }')
          branch_title="Update base and variants to $promoted_sha"
          echo "branch_title=$branch_title" >> $GITHUB_ENV
