# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push

jobs:
  change-detection:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      operator-check-components: ${{ steps.filter_python_simple_check.outputs.operator-check }}
    steps:
      - name: Filter changes for operator
        id: filter_python_simple_check
        uses: actions/github-script@v6
        with:
          script: |
            const changes = ['training-operator', 'inference-operator'];
            const operatorCheck = [
              'inference-operator', 'training-operator'
            ];
            const operatorChanges = changes.filter((change) => operatorCheck.includes(change));
            const operatorNames = operatorChanges.map((element) => element.split('-')[0]);
            core.setOutput('operator-check', operatorNames);
      - name: Convert TOML to JSON
        id: toml-to-json
        run: | 
          python3 -m pip install toml
          python3 -c 'import toml, json, os
          print(os.listdir())
          with open("ci-test-lab/src/config.toml") as file:
            data = toml.load(file)
            json_data = json.dumps(data)
            print(json_data)'
          
        
  checks-matrix:
    name: ${{ matrix.component }} operator checks
    uses: ./.github/workflows/checks.yml
    if: (contains(needs.change-detection.outputs.operator-check-components, 'inference') || contains(needs.change-detection.outputs.operator-check-components, 'training'))
    with:
      ie_type: 'test' #read it from config file
      image_path: 'test' #read it from config file
      docker_image: 'test' #read it from config file
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJSON(needs.change-detection.outputs.operator-check-components) }}
    needs: change-detection