# This is a basic workflow to help you get started with Actions
name: CI Pipeline

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - run: echo ${{ matrix.version }}

  ms-teams-notification:
    needs: [test, lint]
    name: MS Teams Notification
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: MS Teams
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}

# name: CI
# on:
#   workflow_dispatch:
# jobs:
#   example_matrix:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         version: [10, 12, 14]
#     steps:
#       - run: echo ${{ matrix.version }}
  # test:
  #   name: "Run test"
  #   uses: ./.github/workflows/onclosed.yml
  #   secrets: inherit
  #   with:
  #     env_name: daily-test-123
  # ms-teams-notification-success:
  #   needs: test
  #   name: MS Teams Notification
  #   runs-on: ubuntu-latest
  #   if: ${{ always() && github.event.workflow != '.github/workflows/onclosed.yml' }}
  #   steps:
  #     - name: MS Teams
  #       uses: jdcargile/ms-teams-notification@v1.4
  #       with:
  #         github-token: "d32r3232f"
  #         ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
  #         notification-summary: ${{ matrix.val_report }}
  #         notification-color: ${{ steps.col.outputs.color }}
  #         verbose-logging: true
