# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
    inputs:
      vcluster_name:
        type: string
        required: true
        description: Name of vcluster

jobs:
  check-pr:
    name: Check PR status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Convert vcluster_name parameter
        run: |
          vcluster_name_raw=${{ inputs.vcluster_name }}
          vcluster_name_corrected=$(echo $vcluster_name_raw | tr '[:upper:]' '[:lower:]' | tr '/' '-' | tr '_' '-' | tr -cd '[:alnum:]-')
          echo "vcluster_name=$vcluster_name_corrected" >> $GITHUB_ENV
    
  create-preview-env:
    needs: check-pr
    name: create-preview-env
    uses: ./.github/workflows/checks.yml
    with:
      vcluster_name: ${{ env.vcluster_name }}
