# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  change-detection:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      operator-check-components: ${{ steps.filter_python_simple_check.outputs.operator-check }}
      json_data: ${{ steps.read-config.outputs.json_data }}
    steps:
      - uses: actions/checkout@v3
      - name: Build modelmesh-adapter
        env:
          PR_SHA: ${{ github.event.pull_request.merged == true && '' || github.event.pull_request.head.sha }} 
        run: |
          echo ${PR_SHA}
