# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
    inputs:
      vcluster_name:
        type: string
        required: true
        description: Name of vcluster

jobs:
  change-detection:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      operator-check-components: ${{ steps.filter_python_simple_check.outputs.operator-check }}
      json_data: ${{ steps.read-config.outputs.json_data }}
    steps:
      - uses: actions/checkout@v3
      - name: Parameters check
        shell: bash
        run: | 
          [[ ${{ inputs.vcluster_name }} =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ ]] && echo : || (echo "did not match"; exit 1)
