# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  COMP: '["TEST", "TEST2"]'

jobs:
  change-detection:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ toJSON(steps.store_envs.outputs) }}
    steps:
      - name: Store envs
        id: store_envs
        run: |
          echo "COMP=$COMP" >> "$GITHUB_OUTPUT"
  checks-matrix:
    name: ${{ matrix.component }} operator checks
    uses: ./.github/workflows/checks.yml
    with:
      operator_type: ${{ matrix.component }}
    strategy:
      fail-fast: false
      matrix:
        component: ${{fromJSON(needs.change-detection.outputs.envs).COMP}}
