# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
    inputs:
      vcluster_name:
        type: string
        required: true
        description: Name of vcluster

jobs:
  change-detection:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      operator-check-components: ${{ steps.filter_python_simple_check.outputs.operator-check }}
      json_data: ${{ steps.read-config.outputs.json_data }}
    steps:
      - uses: actions/checkout@v3
      - name: Parameters check
        shell: bash
        run: | 
          # vcluster_name=${{ inputs.vcluster_name }}
          # if [[ ${#vcluster_name} -lt 10 ]] &&  [[ $vcluster_name =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ ]]; then
          #   :
          # else
          #   echo -e "vcluster_name doesn't meet required crytiria. It must: \n-contain no more than 253 characters \n-contain only lowercase alphanumeric characters, '-' or '.' \n-start with an alphanumeric character \n-end with an alphanumeric characte"
          #   exit 1
          # fi
  create-preview-env:
    runs-on: ubuntu-latest
    name: create-preview-env
    steps:
      - uses: actions/checkout@v3
      - name: Parameters check
        run: |
          echo "vcluster_name=TEST_VCLUSTER" >> $GITHUB_ENV
          cat .github/workflows/checks.yml
      - name: create-preview-env
        uses: ./.github/workflows/checks.yml
        with:
          vcluster_name: ${{ env.vcluster_name }}
