# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
    inputs:
      vcluster_name:
        type: string
        required: true
        description: Name of vcluster
env:
  BRANCH_NAME: TEST
jobs:
  check-pr:
    name: Check PR status
    runs-on: ubuntu-latest
    outputs: 
      vcluster_name: ${{ steps.convert_params.outputs.vcluster_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Convert vcluster_name parameter
        env:
          EMPTY: ${{ BRANCH_NAME }}
        id: convert_params
        run: |
          echo ${{ EMPTY }}
