# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
jobs:
  test0:
    name: check
    runs-on: ubuntu-latest
    steps:
    - name: Check env
      run: |
        echo "DEBUG 000000"
        echo $GITHUB_STEP_SUMMARY
  test:
    name: "Run test"
    uses: ./.github/workflows/onclosed.yml
    secrets: inherit
    with:
      env_name: daily-test-123
  test2:
    needs: test
    name: Check ENV
    runs-on: ubuntu-latest
    steps:
    - name: Check env
      run: |
        echo "xD"
        echo ${{needs.test.outputs.report_url}}
