# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# env:
#   COMP: '[inference-operator, training-operator]'

jobs:
  checks-matrix:
    name: ${{ matrix.component }} operator checks
    uses: ./.github/workflows/checks.yml
    with:
      operator_type: ${{ matrix.component }}
    strategy:
      fail-fast: false
      matrix:
        component: ${{env.COMP}}
