# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
jobs:
  test:
    name: "Run test"
    uses: ./.github/workflows/onclosed.yml
    secrets: inherit
    with:
      env_name: daily-test-123
  ms-teams-notification-success:
    needs: test
    name: MS Teams Notification
    runs-on: ubuntu-latest
    if: ${{ always() && github.event.workflow != '.github/workflows/onclosed.yml' }}
    strategy:
      matrix:
        val_report: [daily-1, daily-2]
    steps:
      - name: Notf color
        id: col
        run: |
            echo "color=17a2b8" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - name: MS Teams
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: ${{ matrix.val_report }}
          notification-color: ${{ steps.col.outputs.color }}
          verbose-logging: true
