# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  change-detection:
    name: Detect changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Store build params
        id: build_params
        run: |
          branch_title="Update base and variants to 472ada9232da3960e3c43d567bbec2c6fa27b81b 11e3a4fe343996b23e247baac6d4aa8c9b0f194f 79d8561098d832effa21a12ca8356a5047dbb08a"
          echo "branch_title=$branch_title" >> $GITHUB_ENV
