# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
jobs:
  test:
    name: "Run test"
    uses: ./.github/workflows/onclosed.yml
    secrets:
      MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
