# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  change-detection:
    name: Detect changes
    outputs:
      components: [inference-operator, training-operator]

  checks-matrix:
    name: ${{ matrix.component }} operator checks
    uses: ./.github/workflows/checks.yml
    with:
      operator_type: ${{ matrix.component }}
    strategy:
      fail-fast: false
      matrix:
        component: ${{ needs.change-detection.outputs.components }}
    needs:
      - change-detection
