# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
    inputs:
      test:
        type: string
        required: false
        description: Test
jobs:
  test:
    name: "Run test"
    uses: ./.github/workflows/onclosed.yml
