# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
    inputs:
      test:
        type: string
        required: false
        description: Test
jobs:
  # check-pr:
  #   name: Test notification
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Notify dedicated teams channel
  #       uses: jdcargile/ms-teams-notification@v1.4
  #       with:
  #         github-token: ${{ github.token }}
  #         ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
  #         notification-summary: Validation Report
  #         notification-color: 'ffc107'
  #         verbose-logging: true
  # without_optional_params:
  #   name: One with little info
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Microsoft Teams Notification
  #       uses: skitionek/notify-microsoft-teams@master
  #       if: always()
  #       with:
  #         webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
  #         needs: ${{ toJson(needs) }}
  #         job: ${{ toJson(job) }}
  #         steps: ${{ toJson(steps) }}  
  job-1:
    name: fail-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Try to fail
      run: exit 1
  ms-teams-notification-success:
    needs: job-1
    name: MS Teams Notification - Success
    runs-on: ubuntu-latest
    if: always() && success()
    steps:
      - uses: actions/checkout@v4
      - name: MS Teams
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Your custom notification message 
          notification-color: 17a2b8
          verbose-logging: true
  ms-teams-notification-failure:
    needs: job-1
    name: MS Teams Notification - Failure
    runs-on: ubuntu-latest
    if: always() && failure()
    steps:
      - uses: actions/checkout@v4
      - name: MS Teams
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Your custom notification message 
          notification-color: 47a2b1
          verbose-logging: true
  # ms-teams-notification:
  #   name: MS Teams Notification
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Microsoft Teams Notification - success
  #       uses: jdcargile/ms-teams-notification@v1.4
  #       if: success()
  #       with:
  #         github-token: ${{ github.token }} # this will use the runner's token.
  #         ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
  #         notification-summary: Your custom notification message 
  #         notification-color: 17a2b8
  #         verbose-logging: true
  #     - name: Microsoft Teams Notification - failure
  #       uses: jdcargile/ms-teams-notification@v1.4
  #       if: failure()
  #       with:
  #         github-token: ${{ github.token }} # this will use the runner's token.
  #         ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
  #         notification-summary: Your custom notification message 
  #         notification-color: 17a2b8
  #         verbose-logging: true
