# This is a basic workflow to help you get started with Actions

name: Docker_Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  change-detection:
    name: Detect changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker test
        id: docker_test
        run: |
          listofimages="x1 x2 x3 x4 x5 x6 x7"
          counter=0
          IFS=' ' read -ra tagsArray <<< $listofimages
          tagsToDelete=""
          counter=0
          for tag in "${tagsArray[@]}"; do
            if [[ $counter -lt 5 ]]; then
              tagsToDelete+="imageTag=$tag "
              counter=$((counter + 1))
            else
              echo "$tagsToDelete DELETED"
              counter=1
              tagsToDelete="imageTag=$tag "
            fi
          done
          if [[ ! -z "${tagsToDelete}" ]]; then
            echo "$tagsToDelete DELETED"
          fi
