# This is a basic workflow to help you get started with Actions

name: Docker_Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  change-detection:
    name: Detect changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker test
        id: docker_test
        run: |
          echo "::group::aws ecr delete image"
          docker build -t my-echo-app .
          docker run my-echo-app -c "helm version" 
          echo "::endgroup::"
          cat $context/Dockerfile
          echo "XXDDDD"
          cat Dockerfile
