# This is a basic workflow to help you get started with Actions

name: onclosed
on:
  workflow_dispatch:
    inputs:
      env_name:
        type: string
        description: "test"
        required: true
      skip:
        type: boolean
        description: "test"
        default: false
  workflow_call:
    outputs:
      report_url:
        description: Link to the report
        value: ${{ jobs.job-1.outputs.report_url }}        
    inputs:
      env_name:
        type: string
        description: "test"
        required: true
      skip:
        type: boolean
        description: "test"
        default: false

jobs:
  job-1:
    name: success-job
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.generate_report_url.outputs.report_url }}
    steps:
    - uses: actions/checkout@v1
    - name: Success step
      id: generate_report_url
      run: |
        report="www.validation-report.com"
        echo "Test github step summary $report" >> $GITHUB_STEP_SUMMARY
        echo "report_url=$report" >> "$GITHUB_OUTPUT"
  job-2:
    needs: 
      - job-1
    name: fail-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Success step
      run: |
        echo "xD2"
  ms-teams-notification-success:
    needs: job-2
    name: MS Teams Notification
    runs-on: ubuntu-latest
    if: ${{ always() && github.event.workflow != '.github/workflows/onclosed.yml' }}
    steps:
      - name: Notf color
        id: col
        run: |
          if [ "${{ needs.job-2.result }}" == "success" ]; then
            echo "color=17a2b8" >> $GITHUB_OUTPUT
          fi
          if [ "${{ needs.job-2.result }}" == "failure" ]; then
            echo "color=47a2b1" >> $GITHUB_OUTPUT
          fi
          echo "Test github step summary" >> $GITHUB_STEP_SUMMARY
      # - uses: actions/checkout@v4
      # - name: MS Teams
      #   uses: jdcargile/ms-teams-notification@v1.4
      #   with:
      #     github-token: ${{ github.token }} # this will use the runner's token.
      #     ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      #     notification-summary: ${{ github.event.workflow }} - ${{ inputs.env_name }}
      #     notification-color: ${{ steps.col.outputs.color }}
      #     verbose-logging: true
