# This is a basic workflow to help you get started with Actions

name: onclosed
on:
  workflow_dispatch:
    inputs:
      env_name:
        type: string
        description: "test"
        required: true
      skip:
        type: boolean
        description: "test"
        default: false
  workflow_call:
    outputs:
      report_url:
        description: Link to the report
        value: ${{ jobs.job-1.outputs.report_url }}        
    inputs:
      env_name:
        type: string
        description: "test"
        required: true
      skip:
        type: boolean
        description: "test"
        default: false

jobs:
  job-1:
    name: success-job
    runs-on: ubuntu-latest
    outputs:
      report_url: ${{ steps.generate_report_url.outputs.report_url }}
    steps:
    - uses: actions/checkout@v1
    - name: Success step
      id: generate_report_url
      run: |
        report="www.validation-report.com"
        echo "Test github step summary $report" >> $GITHUB_STEP_SUMMARY
        echo "report_url=$report" >> "$GITHUB_OUTPUT"
        echo "DEBUG"
        echo ${{ github.event.workflow }}
