# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_call:
jobs:
  job-1:
    name: success-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Success step
      run: echo "xD"
  job-2:
    needs: job-1
    name: fail-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Fail step
      run: exit 1
  
  ms-teams-notification-success:
    needs: job-2
    name: MS Teams Notification - Success
    runs-on: ubuntu-latest
    if: always() && success()
    steps:
      - uses: actions/checkout@v4
      - name: MS Teams
        run: echo ${{ toJson(github.event) }}
        # uses: jdcargile/ms-teams-notification@v1.4
        # with:
        #   github-token: ${{ github.token }} # this will use the runner's token.
        #   ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        #   notification-summary: "Triggering workflow: ${{ toJson(github.event.workflow) }}"
        #   notification-color: 17a2b8
        #   verbose-logging: true
  ms-teams-notification-failure:
    needs: job-2
    name: MS Teams Notification - Failure
    runs-on: ubuntu-latest
    if: always() && failure()
    steps:
      - uses: actions/checkout@v4
      - name: MS Teams
        run: echo ${{ toJson(github.event) }}
        # uses: jdcargile/ms-teams-notification@v1.4
        # with:
        #   github-token: ${{ github.token }} # this will use the runner's token.
        #   ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        #   notification-summary: "Triggering workflow: ${{ toJson(github.event.workflow) }}" 
        #   notification-color: 47a2b1
        #   verbose-logging: true
  
  #         notification-color: 17a2b8
  #         verbose-logging: true
